### ISSUE TITLE
App crashes when navigating to SemanticZoom page

### ISSUE THREAD

**Issue by DarthMazut** [microsoft/WinUI-Gallery#1356]
### Which version of the app?

WinUI 3 Gallery

### Description

Hello,
I build application locally from `tag: v2.2.0`.

After navigating to SemanticZoom page application crashes.

The unhandled exception is: `System.ArgumentException`: parameter is not valid
here is stacktrace from my local machine:
```
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Markup.IXamlBindingHelperStaticsMethods.ConvertValue(IObjectReference _obj, Type type, Object value)
   at AppUIBasics.ControlPages.SemanticZoomPage.SemanticZoomPage_obj8_Bindings.Update_ImageIconPath(String obj, Int32 phase) in D:\Projekty\CSharp\WinUI 3 Gallery\WinUI-Gallery\WinUIGallery\obj\WinUIGallery\x64\Debug\net6.0-windows10.0.19041.0\win10-x64\ControlPages\SemanticZoomPage.g.cs:line 591
   at AppUIBasics.ControlPages.SemanticZoomPage.SemanticZoomPage_obj8_Bindings.Update_(ControlInfoDataItem obj, Int32 phase) in D:\Projekty\CSharp\WinUI 3 Gallery\WinUI-Gallery\WinUIGallery\obj\WinUIGallery\x64\Debug\net6.0-windows10.0.19041.0\win10-x64\ControlPages\SemanticZoomPage.g.cs:line 578
   at AppUIBasics.ControlPages.SemanticZoomPage.SemanticZoomPage_obj8_Bindings.ProcessBindings(Object item, Int32 itemIndex, Int32 phase, Int32& nextPhase) in D:\Projekty\CSharp\WinUI 3 Gallery\WinUI-Gallery\WinUIGallery\obj\WinUIGallery\x64\Debug\net6.0-windows10.0.19041.0\win10-x64\ControlPages\SemanticZoomPage.g.cs:line 529
   at ABI.Microsoft.UI.Xaml.Markup.IDataTemplateComponent.Do_Abi_ProcessBindings_1(IntPtr thisPtr, IntPtr item, Int32 itemIndex, Int32 phase, Int32* nextPhase)
```

### Windows version

November 2021 Update/21H2 (19044)

**Comment by Jay-o-Way** [comment]
When will the actual (MS Store) app be updated?
