### ISSUE TITLE
WinUI 3 Gallery crashed when clicking Settings button

### ISSUE THREAD

**Issue by ysx93698** [microsoft/WinUI-Gallery#1433]
### WinUI3 Gallery crashes consistently when clicking the setting button.

Step1. Open WinUI3 Gallery.
Step2. Click the bottom-left Settings button.

Then after one pause, the software crashes without any messagebox or error warning or logs.

Some details:

- System version: 22621.3007
- MS Store version: 22312.1401.5.0
- WinUI3 Gallery version: The latest version availible from Microsoft Store  as of this post of this issue.
_Ok, you know I even can't open the settings page:(_

**Comment by DarthMazut** [comment]
Hello, I've just builded version from `eb43dce` and I'm experiencing same issue. It's `InvalidOperationException`: "Sequence contains no elements"; attaching my local stack trace, hope it'll help:
```
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at AppUIBasics.App.get_WinAppSdkRuntimeDetails() in D:\Projekty\Visual MS\Aplikacje\WinUI 3ControlsGallery\Xaml-Controls-Gallery\WinUIGallery\App.xaml.cs:line 54
   at AppUIBasics.SettingsPage.get_WinAppSdkRuntimeDetails() in D:\Projekty\Visual MS\Aplikacje\WinUI 3ControlsGallery\Xaml-Controls-Gallery\WinUIGallery\SettingsPage.xaml.cs:line 37
   at AppUIBasics.SettingsPage.SettingsPage_obj1_Bindings.Update_(SettingsPage obj, Int32 phase) in D:\Projekty\Visual MS\Aplikacje\WinUI 3ControlsGallery\Xaml-Controls-Gallery\WinUIGallery\obj\WinUIGallery\x86\Debug\net7.0-windows10.0.19041.0\win10-x86\SettingsPage.g.cs:line 164
   at AppUIBasics.SettingsPage.SettingsPage_obj1_Bindings.Update() in D:\Projekty\Visual MS\Aplikacje\WinUI 3ControlsGallery\Xaml-Controls-Gallery\WinUIGallery\obj\WinUIGallery\x86\Debug\net7.0-windows10.0.19041.0\win10-x86\SettingsPage.g.cs:line 123
   at AppUIBasics.SettingsPage.SettingsPage_obj1_Bindings.Initialize() in D:\Projekty\Visual MS\Aplikacje\WinUI 3ControlsGallery\Xaml-Controls-Gallery\WinUIGallery\obj\WinUIGallery\x86\Debug\net7.0-windows10.0.19041.0\win10-x86\SettingsPage.g.cs:line 117
   at AppUIBasics.SettingsPage.SettingsPage_obj1_Bindings.Loading(FrameworkElement src, Object data) in D:\Projekty\Visual MS\Aplikacje\WinUI 3ControlsGallery\Xaml-Controls-Gallery\WinUIGallery\obj\WinUIGallery\x86\Debug\net7.0-windows10.0.19041.0\win10-x86\SettingsPage.g.cs:line 153
   at WinRT._EventSource_global__Windows_Foundation_TypedEventHandler_global__Microsoft_UI_Xaml_FrameworkElement__object_.EventState.<GetEventInvoke>b__1_0(FrameworkElement sender, Object args)
   at ABI.Windows.Foundation.TypedEventHandler`2.Do_Abi_Invoke[TSenderAbi,TResultAbi](Void* thisPtr, TSenderAbi sender, TResultAbi args)
```

**Comment by ysx93698** [comment]
Thank you! This issue has been fixed in the latest version.
